parameters:
    ku_menu.yml_provider.class: KuManuel\Bundle\MenuBundle\Menu\Provider\YmlProvider

services:
    ku_menu.yml_provider:
        class: %ku_menu.yml_provider.class%
        arguments: ["@knp_menu.factory", %ku_menu.menus%]
        tags:
            - { name: knp_menu.provider }
